  # Just like the config/database.yml this file requires an entry for each environment
  # http://aws.amazon.com/security-credentials
  development:
    access_key_id: AKIAIMLXHZMLCIYL2SEA
    secret_access_key: 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
  production:
    access_key_id: AKIAIMLXHZMLCIYL2SEA
    secret_access_key: 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
  test:
    access_key_id: AKIAIMLXHZMLCIYL2SEA
    secret_access_key: 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